name: Python Build and Test

on:
  push:
    branches:
      - main  # Change this to your default branch name if different
  pull_request:
    branches:
      - main  # Change this to your default branch name if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12.3  # Change this to the Python version you're using

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Replace 'requirements.txt' with your requirements file name

      - name: Build Docker Image
        run: docker build -t myimage .
